# Generated by Django 3.2.15 on 2022-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dat_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
