# Generated by Django 3.2.15 on 2023-02-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_dat_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_file_parent', to='file.file'),
        ),
    ]
