# Generated by Django 3.2.15 on 2023-04-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_groupaccount_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupaccount',
            name='profile',
        ),
    ]
