# Generated by Django 3.2.15 on 2022-12-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='city',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='language',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='region',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='status',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='uf',
            name='deleted_by',
        ),
    ]
