# Generated by Django 3.2.15 on 2023-04-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20230406_2205'),
        ('core', '0002_dynamictexttranslation_systemlanguages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicTextTranslation',
        ),
    ]
