# Generated by Django 3.2.15 on 2023-04-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_dynamictexttranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLanguages',
        ),
    ]
