# Generated by Django 4.2.3 on 2023-08-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
