# Generated by Django 3.2.14 on 2022-08-18 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_state_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cep_faixa_ini', models.CharField(max_length=80, null=True)),
                ('cep_faixa_fim', models.CharField(max_length=80, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_city_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_city_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_city_last_edit', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.state')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='uf',
        ),
        migrations.DeleteModel(
            name='Cep',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
