# Generated by Django 4.2.3 on 2023-08-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
