# Generated by Django 3.2.15 on 2022-09-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220909_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelTable(
            name='city',
            table='public"."city',
        ),
    ]
