# Generated by Django 3.2 on 2022-08-08 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador da conta')),
                ('nm_bank', models.CharField(max_length=150, null=True, verbose_name='Nome da conta')),
                ('description', models.TextField(null=True, verbose_name='Desrição da conta')),
                ('branch', models.IntegerField(null=True)),
                ('branch_formatted', models.CharField(max_length=30, null=True)),
                ('account_number', models.IntegerField(null=True)),
                ('digit', models.SmallIntegerField(null=True)),
                ('account_number_formatted', models.CharField(max_length=150, null=True)),
                ('dat_start', models.DateField(help_text='Data de início do contrato', null=True)),
                ('dat_end', models.DateField(help_text='Data de fim do contrato', null=True)),
                ('is_pj', models.BooleanField(default=False, null=True)),
                ('is_debit', models.BooleanField(default=False, help_text='Indica se a conta tem possibilidade de cartão de débito', null=True)),
                ('is_credit', models.BooleanField(default=False, help_text='Indica se a conta tem possibilidade de cartão de crédito', null=True)),
                ('is_investment', models.BooleanField(default=False, help_text='Indica se a conta é para aplicações financeiras')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankaccount_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankaccount_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankaccount_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."bank_account',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('dat_start', models.DateField(help_text='Data de início do contrato', null=True)),
                ('dat_end', models.DateField(help_text='Data de fim do contrato', null=True)),
                ('dat_payment', models.IntegerField(null=True)),
                ('dat_threshold', models.IntegerField(help_text='Data de fechamento da fatura', null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcard_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcard_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcard_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."credit_card',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InvestimentType',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investimenttype_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investimenttype_deleted', to=settings.AUTH_USER_MODEL)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investimenttype')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investimenttype_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."investment_type',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('dat_investment', models.DateField(null=True)),
                ('qtd_titles', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_investiment', models.DecimalField(decimal_places=2, help_text='Preço do título no momento da compra', max_digits=10, null=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profit_contracted', models.CharField(help_text='Rentabilidade a ser recebida se o título for mantido até o vencimento', max_length=200, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_last_edit', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investimenttype')),
            ],
            options={
                'db_table': 'finance"."investment',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('refefence', models.IntegerField(help_text='Anomes de referência', null=True)),
                ('dat_payment', models.DateField(null=True)),
                ('dat_purchase', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Sempre em reais, valor final', max_digits=14)),
                ('currency', models.CharField(choices=[('BRL', 'R$ - Real'), ('EUR', '€ - Euro'), ('USD', '$ - Dólar'), ('CZK', 'Kč - Coroa Tcheca')], default='BRL', max_length=30)),
                ('amount_currency', models.DecimalField(decimal_places=2, help_text='Sempre real da compra, na moeda original', max_digits=14, null=True)),
                ('price_dollar', models.DecimalField(decimal_places=5, help_text='Usado em compra em outra moeda, em relação ao real', max_digits=14, null=True)),
                ('price_currency_dollar', models.DecimalField(decimal_places=5, help_text='Valor da moeda em relação ao dolar, usado na conversão', max_digits=14, null=True)),
                ('iof', models.DecimalField(decimal_places=2, default=0, help_text='Iof total da compra, quando aplicável', max_digits=7, null=True)),
                ('stallment', models.SmallIntegerField(default=1, null=True)),
                ('tot_stallment', models.SmallIntegerField(default=1, null=True)),
                ('is_stallment', models.BooleanField(default=False, null=True)),
                ('description', models.TextField(null=True)),
                ('origin', models.CharField(default='SISTEMA', max_length=50, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcardbill_created', to=settings.AUTH_USER_MODEL)),
                ('credit_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.creditcard')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcardbill_deleted', to=settings.AUTH_USER_MODEL)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.creditcardbill')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcardbill_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."creditcard_bill',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorygroup_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorygroup_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorygroup_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."category_group',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('reference', models.IntegerField(help_text='Anomes de referência', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dat_purchase', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bankaccount')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankstatement_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankstatement_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankstatement_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."bank_statement',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
