# Generated by Django 3.2.15 on 2023-04-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditcardbill',
            table='finance"."credit_card_bill',
        ),
    ]
