# Generated by Django 4.2.3 on 2023-09-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='period',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='accountstatement',
            old_name='period',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='period',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='investmentbalance',
            old_name='period',
            new_name='reference',
        ),
    ]
