# Generated by Django 4.2.7 on 2024-01-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(help_text='Descrição da conta', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.accounttype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
