# Generated by Django 3.2 on 2022-08-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='refefence',
            new_name='reference',
        ),
    ]
