# Generated by Django 4.2.3 on 2023-09-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_period_accountbalance_reference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
