# Generated by Django 3.2.15 on 2022-12-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20221212_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='is_stallment',
            new_name='is_installment',
        ),
    ]
