# Generated by Django 3.2.15 on 2022-12-09 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20221208_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankaccount_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bankstatement_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorygroup_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorytype_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcard_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_creditcardbill_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currency',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currency_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currencyrate_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investimenttype',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investimenttype_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentstatement',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investmentstatement_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
