# Generated by Django 3.2 on 2022-08-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_refefence_creditcardbill_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbill',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=-1, help_text='Total da compra, quando existe parcelas', max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Sempre em reais, valor final na fatura', max_digits=14),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='is_stallment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='origin',
            field=models.CharField(default='SYSTEM', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='stallment',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='tot_stallment',
            field=models.SmallIntegerField(default=1),
        ),
    ]
