# Generated by Django 3.2.15 on 2023-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_creditcardbill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='bank_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Spread do banco', max_digits=7),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='price_dollar',
            field=models.DecimalField(decimal_places=5, help_text='Para conta em outras moedas', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Iof total da compra, quando aplicável', max_digits=7),
        ),
    ]
