# Generated by Django 3.2 on 2022-08-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20220810_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardbill',
            name='iof',
        ),
        migrations.AddField(
            model_name='creditcardbill',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Iof total da compra, quando aplicável', max_digits=7),
        ),
    ]
