# Generated by Django 3.2.15 on 2022-12-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20221208_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='categorygroup',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='categorytype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='creditcardbill',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investimenttype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investmentstatement',
            name='deleted_by',
        ),
    ]
