# Generated by Django 3.2.15 on 2023-04-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20230404_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='perc_bank_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentagem de spread do banco', max_digits=7),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='perc_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentagem do IOF', max_digits=7),
        ),
    ]
