# Generated by Django 3.2.15 on 2023-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_is_stallment_creditcardbill_is_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
