# Generated by Django 4.2.3 on 2023-09-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accountbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='reference',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='accountstatement',
            old_name='reference',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='reference',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='financedata',
            old_name='reference',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='investmentbalance',
            old_name='reference',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='investmentstatement',
            old_name='reference',
            new_name='period',
        ),
    ]
