# Generated by Django 3.2.15 on 2023-02-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='currency',
            field=models.ForeignKey(default='BRL', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.currency'),
            preserve_default=False,
        ),
    ]
