# Generated by Django 4.2.3 on 2023-08-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financedata_delete_brazilinterestrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceData',
        ),
    ]
