# Generated by Django 3.2 on 2022-08-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20220810_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='group',
            field=models.CharField(choices=[('fixed_expenses', 'Despesas fixas'), ('variable_expenses', 'Despesas variáveis')], default='variable_expenses', max_length=50),
        ),
    ]
