# Generated by Django 4.2.3 on 2023-10-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_reference_accountbalance_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstatement',
            old_name='dat_purchase',
            new_name='purchased_at',
        ),
    ]
