# Generated by Django 3.2.15 on 2022-08-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_alter_categorygroup_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currency_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currency_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currency_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."currency',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=15, max_digits=30)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currencyrate_base', to='finance.currency')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currencyrate_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currencyrate_currency', to='finance.currency')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currencyrate_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_currencyrate_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."currency_rate',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
