# Generated by Django 3.2.15 on 2023-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20230404_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='amount_reference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
