# Generated by Django 3.2.15 on 2022-09-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_currency_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='maturity',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='InvestmentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('reference', models.IntegerField(null=True)),
                ('gross_profit_annual', models.CharField(help_text='Taxa equivalente a 1 ano', max_length=200, null=True)),
                ('gross_profit', models.CharField(help_text='Da aplicação até hoje', max_length=200, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('investment_time', models.IntegerField(help_text='Dias corridos, contados a partir da data de liquidação do investimento', null=True)),
                ('ir_tax_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ir_tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iof_tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('b3_tax', models.DecimalField(decimal_places=2, help_text='Taxa de custódia da B3', max_digits=10, null=True)),
                ('bank_tax', models.DecimalField(decimal_places=2, help_text='Taxa de custódia da instituição finenceira', max_digits=10, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Valor para resgate antecipado, ou seja, antes do vencimento do título', max_digits=10, null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investmentstatement_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investmentstatement_deleted', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investment')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investmentstatement_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"finance"."investment_statement"',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
