# Generated by Django 3.2.15 on 2023-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20230224_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='investmentstatement',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='investmentstatement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investmentstatement',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investmentstatement',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentstatement',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='investmenttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investmenttype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investmenttype',
            name='father',
        ),
        migrations.RemoveField(
            model_name='investmenttype',
            name='last_edited_by',
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='price_currency_dollar',
            field=models.DecimalField(decimal_places=5, help_text='Valor da moeda em relação ao dólar, usado na conversão', max_digits=14, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentStatement',
        ),
        migrations.DeleteModel(
            name='InvestmentType',
        ),
    ]
