# Generated by Django 4.2.3 on 2023-08-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_type'),
        ('finance', '0006_financedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedata',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financedata',
            name='periodicity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.type'),
        ),
    ]
