# Generated by Django 4.2.3 on 2023-10-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_dat_purchase_accountstatement_purchased_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountstatement',
            table='finance"."account_statement',
        ),
    ]
