# Generated by Django 3.2.15 on 2023-04-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bankstatement_amount_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='currency_reference',
            field=models.ForeignKey(default='BRL', help_text='Moeda de referência', on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_statement_currency_reference', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='effective_rate',
            field=models.DecimalField(decimal_places=5, help_text='VET: valor efetivo total. valor total do câmbio com as taxas e impostos', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='amount_reference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total na moeda de referência, no caso de câmbio, senão o mesmo valor de amount', max_digits=14),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='price_dollar',
            field=models.DecimalField(decimal_places=5, help_text='Para conta em outras moedas, em relação a moeda de referência', max_digits=14, null=True),
        ),
    ]
