# Generated by Django 3.2.15 on 2022-09-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20220904_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardbill',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.currency'),
        ),
    ]
