# Generated by Django 3.2.15 on 2023-04-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20230404_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='amount_reference',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='bank_fee',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='currency_reference',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='effective_rate',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='perc_bank_fee',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='perc_tax',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='price_dollar',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='tax',
        ),
    ]
