# Generated by Django 4.2.3 on 2023-08-10 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_tipo'),
        ('finance', '0007_financedata_value_alter_financedata_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedata',
            name='type',
            field=models.ForeignKey(default='2a2b100f-17d9-4c61-b3b4-f06662113953', help_text='O tipo da informação (cdi, selic, ipca, etc)', on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_data_type', to='core.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financedata',
            name='periodicity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_data_periodicity', to='core.type'),
        ),
    ]
