# Generated by Django 4.2.3 on 2023-08-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financedata_type_alter_financedata_periodicity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='amount_currency',
            new_name='amount_reference',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='currency',
            new_name='currency_reference',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='price_dollar',
            new_name='dollar_quote',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='father',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='dat_payment',
            new_name='payment_at',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='dat_purchase',
            new_name='purchase_at',
        ),
    ]
