# Generated by Django 4.2.3 on 2023-11-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_dat_created_account_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dat_close',
            new_name='close_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='dat_open',
            new_name='open_at',
        ),
        migrations.RenameField(
            model_name='accountstatement',
            old_name='purchased_at',
            new_name='purchase_at',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='dat_closing',
            new_name='closing_at',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='dat_due',
            new_name='due_at',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='dat_end',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='dat_start',
            new_name='start_at',
        ),
    ]
