# Generated by Django 3.2.15 on 2023-03-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_investment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
