# Generated by Django 3.2.15 on 2022-09-04 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220818_1205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_alter_creditcardbill_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('incoming', 'Entrada'), ('outcoming', 'Saída'), ('investment', 'Investimentos')], max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorytype_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorytype_deleted', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_categorytype_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."category_type',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
