# Generated by Django 4.2.3 on 2023-08-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_amount_currency_creditcardbill_amount_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardbill',
            name='amount_reference',
            field=models.DecimalField(decimal_places=2, help_text='O valor da compra', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='currency_reference',
            field=models.ForeignKey(help_text='A moeda da compra', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='dollar_quote',
            field=models.DecimalField(decimal_places=5, help_text='Valor do dólar em relação a moeda do cartão', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='price_currency_dollar',
            field=models.DecimalField(decimal_places=5, help_text='Valor do dólar em relação a moeda original, em caso de compra em uma terceira moeda', max_digits=14, null=True),
        ),
    ]
