# Generated by Django 4.2.3 on 2023-11-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_dat_close_account_close_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_investment',
            field=models.BooleanField(default=False),
        ),
    ]
