# Generated by Django 3.2.15 on 2022-09-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_categorytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='stallment',
            new_name='installment',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='tot_stallment',
            new_name='tot_installment',
        ),
    ]
