# Generated by Django 3.2.15 on 2023-04-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_investmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='type',
            field=models.ForeignKey(default='3033e4b2-51c5-4d9f-9b55-b286d095ebd4', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investmenttype'),
            preserve_default=False,
        ),
    ]
