# Generated by Django 3.2.15 on 2023-03-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='cash_flow',
            field=models.CharField(choices=[('OUTGOING', 'Saída'), ('INCOMING', 'Entrada')], default='OUTGOING', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardbill',
            name='cash_flow',
            field=models.CharField(choices=[('OUTGOING', 'Saída'), ('INCOMING', 'Entrada')], default='OUTGOING', max_length=100),
            preserve_default=False,
        ),
    ]
