# Generated by Django 3.2.15 on 2022-09-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20220904_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investimenttype',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentstatement',
            name='dat_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
