# Generated by Django 4.2.3 on 2023-08-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_rename_price_currency_dollar_creditcardbill_dollar_currency_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='account_old',
        ),
    ]
