# Generated by Django 3.2.15 on 2022-09-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20220909_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='origin',
            field=models.CharField(default='SYSTEM', max_length=50),
        ),
    ]
