# Generated by Django 3.2.15 on 2023-04-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dynamictexttranslation_systemlanguages'),
        ('finance', '0011_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttype',
            name='dynamic_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_type_dynamic_description', to='core.dynamictexttranslation'),
        ),
        migrations.AddField(
            model_name='investmenttype',
            name='dynamic_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_type_dynamic_name', to='core.dynamictexttranslation'),
        ),
    ]
