# Generated by Django 3.2.15 on 2023-04-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20230406_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmenttype',
            name='dynamic_description',
        ),
        migrations.RemoveField(
            model_name='investmenttype',
            name='dynamic_name',
        ),
    ]
