# Generated by Django 3.2.15 on 2022-10-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20220925_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='dat_threshold',
            new_name='dat_closing',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='dat_payment',
            new_name='dat_due',
        ),
    ]
