# Generated by Django 4.2.3 on 2023-12-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_cashflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
