# Generated by Django 4.2.3 on 2023-08-15 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0013_rename_bankstatement_accountstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_last_edited', models.DateTimeField(blank=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField(help_text='Período de referência')),
                ('transactions', models.DecimalField(decimal_places=2, help_text='Soma de todas as transações realizadas na conta no período', max_digits=14)),
                ('earnings', models.DecimalField(decimal_places=2, help_text='Soma de todos os rendimentos da conta no período', max_digits=14)),
                ('transactions_balance', models.DecimalField(decimal_places=2, help_text='Saldo da movimentação da conta no período', max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Saldo da conta no período', max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.accountstatement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_last_edit_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."account_balance',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Iof total da compra, quando aplicável', max_digits=14),
        ),
        migrations.DeleteModel(
            name='BankAccountMonthlyBalance',
        ),
    ]
