# Generated by Django 3.2.15 on 2023-04-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20230406_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investment'),
        ),
    ]
