# Generated by Django 4.2.3 on 2023-08-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_accountbalance_alter_creditcardbill_tax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
