# Generated by Django 4.2.3 on 2023-12-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_cashflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='period',
            new_name='reference',
        ),
    ]
