# Generated by Django 3.2.15 on 2023-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_investment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='cash_flow',
            field=models.CharField(choices=[('OUTGOING', 'Saída'), ('INCOMING', 'Entrada')], default='INCOMING', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='period',
            field=models.IntegerField(default=202501, help_text='Período de referência'),
            preserve_default=False,
        ),
    ]
