# Generated by Django 3.2.15 on 2022-11-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20221105_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='price_investiment',
            new_name='price_investment',
        ),
    ]
