# Generated by Django 4.2.3 on 2023-12-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_rename_period_creditcardbill_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='reference',
            new_name='period',
        ),
    ]
