# Generated by Django 3.2.15 on 2023-03-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_bankaccountmonthlybalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='cash_flow',
            field=models.CharField(choices=[('OUTGOING', 'Saída'), ('INCOMING', 'Entrada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='creditcardbill',
            name='cash_flow',
            field=models.CharField(choices=[('OUTGOING', 'Saída'), ('INCOMING', 'Entrada')], max_length=100),
        ),
    ]
