# Generated by Django 3.2.15 on 2023-04-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20230411_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='parent_id',
        ),
    ]
