# Generated by Django 4.2.7 on 2024-01-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_rename_reference_creditcardbill_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentStatement',
        ),
    ]
