# Generated by Django 3.2.15 on 2023-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20230316_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmonthlybalance',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccountmonthlybalance',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
