# Generated by Django 3.2.15 on 2022-11-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_rename_price_investiment_investment_price_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentstatement',
            old_name='reference',
            new_name='period',
        ),
    ]
