# Generated by Django 4.2.3 on 2023-08-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_accountbalance_incoming_accountbalance_outgoing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentStatement',
        ),
    ]
