# Generated by Django 3.2.15 on 2023-04-12 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_remove_investment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investment'),
        ),
    ]
