# Generated by Django 3.2.15 on 2023-03-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20230317_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccountMonthlyBalance',
        ),
    ]
