# Generated by Django 3.2.15 on 2022-11-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_rename_reference_investmentstatement_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='reference',
            new_name='period',
        ),
    ]
