# Generated by Django 3.2.15 on 2022-11-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_rename_reference_creditcardbill_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='reference',
            new_name='period',
        ),
    ]
