# Generated by Django 4.2.7 on 2024-01-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_taxfeetype_delete_investmentbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxFeeType',
        ),
    ]
