# Generated by Django 3.2.15 on 2023-04-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_investment_dat_maturity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountmonthlybalance',
            name='account',
        ),
    ]
