# Generated by Django 4.2.3 on 2023-08-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_accountbalance_previous_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceData',
        ),
    ]
