# Generated by Django 3.2.15 on 2023-04-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_remove_bankaccountmonthlybalance_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmonthlybalance',
            name='account',
            field=models.ForeignKey(default='32e542e7-bf2b-4408-b724-798591f11e09', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.account'),
            preserve_default=False,
        ),
    ]
