# Generated by Django 3.2.15 on 2023-03-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_account_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
