# Generated by Django 4.2.3 on 2023-08-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_index_financedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='index',
            field=models.ForeignKey(default='b7e5c4a0-3b65-4b1f-86d8-3797ef1a91a0', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.index'),
            preserve_default=False,
        ),
    ]
