# Generated by Django 3.2.15 on 2023-03-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='custodian',
            field=models.ForeignKey(default='b9758bb0-6f76-405d-a1af-3e4fb4cf4254', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bank'),
            preserve_default=False,
        ),
    ]
