# Generated by Django 4.2.7 on 2024-01-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_investment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='liquidated_amount',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
