# Generated by Django 4.2.3 on 2023-09-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_rename_dat_maturity_investment_maturity_at_liquidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_liquidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='liquidated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='liquidity',
            field=models.ForeignKey(default='ea84f643-bea4-4cad-ac7b-1b848d9aeeb7', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.liquidity'),
            preserve_default=False,
        ),
    ]
