# Generated by Django 3.2.15 on 2023-03-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20230326_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='account',
            new_name='account_old',
        ),
    ]
