# Generated by Django 4.2.7 on 2024-01-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_rename_cashflow_posstatement_cash_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posstatement',
            name='method',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
