# Generated by Django 3.2.15 on 2023-03-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_rename_account_bankstatement_account_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='account',
            field=models.ForeignKey(default='a7b2cb0c-c64e-4623-9673-72c6205ad2e1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_statement_account', to='finance.account'),
            preserve_default=False,
        ),
    ]
