# Generated by Django 4.2.3 on 2023-09-07 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0025_investment_is_liquidated_investment_liquidated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, help_text='Saldo da conta no período anterior', max_digits=14),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='transactions_balance',
            field=models.DecimalField(decimal_places=2, help_text='Soma das entradas e saídas mais os rendimentos', max_digits=14),
        ),
        migrations.CreateModel(
            name='InvestmentBalance',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_last_edited', models.DateTimeField(blank=True, null=True)),
                ('dat_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period', models.IntegerField(help_text='Período de referência')),
                ('previous_balance', models.DecimalField(decimal_places=2, help_text='Saldo dos investimentos no período anterior', max_digits=14)),
                ('incoming', models.DecimalField(decimal_places=2, help_text='Todas as entradas no período', max_digits=14)),
                ('outgoing', models.DecimalField(decimal_places=2, help_text='Todas as saídas no período', max_digits=14)),
                ('transactions', models.DecimalField(decimal_places=2, help_text='Saldo de entradas e saídas', max_digits=14)),
                ('earnings', models.DecimalField(decimal_places=2, help_text='Soma de todos os rendimentos investimentos no período', max_digits=14)),
                ('transactions_balance', models.DecimalField(decimal_places=2, help_text='Soma das entradas e saídas mais os rendimentos', max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Saldo do investimento no período', max_digits=14)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.investment')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_last_edit_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance"."investment_balance',
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
