# Generated by Django 3.2.15 on 2023-03-27 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0026_bankstatement_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='owner',
            field=models.ForeignKey(default='adf52a1e-7a19-11ed-a1eb-0242ac120002', on_delete=django.db.models.deletion.DO_NOTHING, to='user.account'),
            preserve_default=False,
        ),
    ]
