# Generated by Django 4.2.7 on 2024-01-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_posstatement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posstatement',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
