# Generated by Django 4.2.7 on 2024-01-28 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_investmentgoal_investmentgoalallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentgoal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e185b43-959e-44b7-a390-32953825b966'), primary_key=True, serialize=False),
        ),
    ]
