# Generated by Django 3.2.15 on 2023-03-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20230327_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='account_old',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bankaccount'),
        ),
    ]
