# Generated by Django 4.2.7 on 2024-01-28 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0029_alter_investmentgoal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentgoal',
            name='owner',
            field=models.ForeignKey(default='adf52a1e-7a19-11ed-a1eb-0242ac120002', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f98c31a-2f40-4adc-9cb6-b81cee510fd1'), primary_key=True, serialize=False),
        ),
    ]
