# Generated by Django 3.2.15 on 2023-03-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20230329_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='owner_old',
        ),
        migrations.RenameField(
            model_name='bankstatement',
            old_name='owner',
            new_name='owner_old',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='owner',
            new_name='owner_old',
        ),
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='owner',
            new_name='owner_old',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='owner',
            new_name='owner_old',
        ),
    ]
