# Generated by Django 4.2.7 on 2024-01-29 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_creditcardbill_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentgoal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b846b5a1-f433-4a24-b255-27b3ec57dcc8'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
