# Generated by Django 3.2.15 on 2023-03-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221212_2135'),
        ('finance', '0031_auto_20230330_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default='0b25ad2a-934c-405e-99fd-36fdedb429fd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_account_owner', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='owner',
            field=models.ForeignKey(default='0b25ad2a-934c-405e-99fd-36fdedb429fd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_bank_statement_owner', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(default='0b25ad2a-934c-405e-99fd-36fdedb429fd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_credit_card_owner', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardbill',
            name='owner',
            field=models.ForeignKey(default='0b25ad2a-934c-405e-99fd-36fdedb429fd', on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='owner',
            field=models.ForeignKey(default='0b25ad2a-934c-405e-99fd-36fdedb429fd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_investment_owner', to='user.user'),
            preserve_default=False,
        ),
    ]
