# Generated by Django 3.2.15 on 2023-03-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20230330_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='creditcardbill',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='owner',
        ),
    ]
