# Generated by Django 4.2.7 on 2024-01-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_alter_investmentgoal_id_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardbill',
            old_name='credit_card',
            new_name='credit_card_old',
        ),
    ]
