# Generated by Django 4.2.7 on 2024-01-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_rename_credit_card_creditcardbill_credit_card_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbill',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.creditcard'),
        ),
    ]
