# Generated by Django 3.2.15 on 2022-12-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_by',
        ),
    ]
