# Generated by Django 3.2.15 on 2022-12-13 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_dat_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hash',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
